services:
  - type: web
    name: miniapp-backend
    env: node
    region: frankfurt
    plan: free
    
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
